### ISSUE TITLE
Clean Up

### ISSUE THREAD

**Issue by turtlestv** [I-A-C/LambdaScrapers#11]
As @dok-desuka said
"Hi. You have 3 copies of LambdaScrapers in your account: the LambdaScrapers repo, the LambdaScrapersRepo repo and another one in the ExodusReduxRepo repo.

My suggestions:

Take the code from LambdaScrapersRepo, as that seems to be the most recent.
Put all that code in the LambdaScrapers repo, the original.
Delete LambdaScrapersRepo. You can do that at the bottom of the settings page.
Rename LambdaScrapers repo to script.module.lambdascrapers, you do that on the settings page page as well, at the top. Then make the files directly represent the contents of the folder.
Rename the ExodusReduxRepo repo to plugin.video.exodusredux.
Create a repo named zips or I-A-C-Repo or something like that. Make this your Kodi repository source, with an addons.md5 and addons.xml etc. It should contain the distribution folders for all your add-ons, like you're already doing with them."

I agree keep things in unity. 

I have have updated your lambda on my stuff to 1.5.2. using my repo. If you need help we are here.

**Comment by doko-desuka** [comment]
Forgot to add, the reason for doing this is to have a single place for people to send pull-requests. There'll be a single lambdascrapers and a single exodusredux project.

**Comment by turtlestv** [comment]
I agree entirely. There is a scrappers setup but not merges or updates. I think he stated he is fairly new to git so he may need help.

**Comment by turtlestv** [comment]
I'm going to send a pull request to that one tonight with the current commits. If it gets merged and repo fixed then we are good

**Comment by doko-desuka** [comment]
Hmm maybe they could add you as a collaborator? The page to manage collaborators is this: https://github.com/I-A-C/LambdaScrapers/invitations

**Comment by SerpentDrago** [comment]
Agree it could use a complete re cleanup . but as it exists , any pull requests just submit to https://github.com/I-A-C/ExodusReduxRepo


It was fairly obvious to me that that was the repo that is being updated moving forward . most if not ALL the existing pull requests are done on that one . I went though all the others and made sure .

**Comment by SerpentDrago** [comment]
https://github.com/I-A-C/ExodusReduxRepo/tree/master/script.module.lambdascrapers 

is the current updated version of Lambdascrapers . just roll with it till he mybee cleans up . I hope he just deletes this and the other repo  .

**Comment by turtlestv** [comment]
Response added to #12
