### ISSUE TITLE
A few checked

### ISSUE THREAD

**Issue by jewbmx** [I-A-C/LambdaScrapers#5]
These are from ALL-en_DebridOnly...
(Double check advised, my check is with firefox in the us.)

_Down
-ddls.py - http://www.ddlseries.pw
-rlsmovies.py - http://www.rls-movies.com
(new url is http://scene-rls.net  and already in scenerls.py)
-tvrelease.py - http://tv-release.pw

_Ddos
-gomovies.py - http://gomovies.gs
-rlsscn.py - http://rlsscn.in
-sceper.py - https://sceper.unblocked.pro
-seriescr.py - http://seriescr.com
-wrzcraft.py - http://wrzcraft.net

_Fix
-myvideolink.py
Old:
http://iwantmyshow.net
New:
http://iwantmyshow.tk
http://myvideolinks.net
(self.domains are all dead besides first and last, all lead to the new 2.)

_Note
-3 releasebb.
-These redirect to their new urls, might wanna change em over maybe.
phazedll.py
power.py

**Comment by jewbmx** [comment]
I'll keep adding to this post as i finish folders if ya want, gonna be a little slow in my spare time lol

**Comment by jewbmx** [comment]
These are from ALL-en_Master...

_All-Master

_Down
123moviesgold.py - http://123movies.gold
4kmovieto.py - https://movie4kto.st (has offline version)(update to http://movie4k.is)
allrls.py - http://bestrls.net (update to http://oorls.xyz)
animeultima.py - http://www.animeultima.io (update to https://animeultima.eu)
dizigold.py - http://www.dizigold2.com
filmfrantic.py - http://filmfrantic.com
fmovied6.py - http://freemoviedownloads6.com
freemovie6.py - http://freemoviedownloads6.com
hdpopcorns.py - http://hdpopcorns.co
imdark.py - http://imdark.com
locker.py - http://www2.putlocker.io (new url is http://putlocker.co)
miradetodo.py - http://miradetodo.io (new url is https://miradetodo.net)
movie4uch.py - http://movie4u.ch (new url is https://movie4u.live)
mzmovies.py - https://www.mehlizmovies.com
rajahoki88.py - http://rajahoki88.com


_Ban
onlinedizi.py - http://onlinedizi.com (us block)


_Ddos
flenix.py - http://flenix.org
m4ufree.py - http://m4ufree.net (http://m4ufree.tv is ddos free and from my bookmarks lol)
plocker.py - https://www5.putlockertv.to
vodly.py - http://watch32.is (https://watch32.la is ddos free)


_Fix
dltube.py - https://www.mydownloadtube.to (seems broke but .com works fine.)
filmxy.py - https://www.filmxy.me (all works but should update to https://www.filmxy.one since both self domains redirect to it.)
icouchtuner.py - http://ecouchtuner.to (works but should update url http://ecouchtuner.city redirects already.)
megahd.py - http://megashare.bz (redirects to https://onlinemoviewatching.com)
mywatchseries.py - http://mywatchseries.to (redirects to https://www1.swatchseries.to)
pron.py - https://pron.tv (redirects to https://www.mypron.tv)
watch-free.py - http://dwatchseries.to (redirects to https://www1.swatchseries.to)
xwatchseries.py - http://dwatchseries.to (redirects to https://www1.swatchseries.to)


_Note
xmovies.py might have ddos was taking a dab, could update to https://xmovies8.pl
pretty sure kattv.py and darewatch.py are "super searchers" that might not be needed or wanted.

working url found randomly you might want https://cartoonhd.care

**Comment by jewbmx** [comment]
Im gonna stop there unless youd like me to go thru any other folders. You might wanna double check my findings, this is all just simple browser checks thru a cell phone after all lol.

**Comment by jewbmx** [comment]
Found a new fix to add for ya. These are two replacement urls for  ddls.py

http://ddlseries.rssing.com
https://en.ddl.me

**Comment by doko-desuka** [comment]
When it's a matter of address updates, you can go in and propose changes yourself.  

For example, that "FilmXY" site that changed from **.me** to **.one**:  
You log in to Github as you are, go to the [online file](https://github.com/I-A-C/LambdaScrapers/blob/master/script.module.lambdascrapers/lib/lambdascrapers/sources_ALL/en_Master/filmxy.py#L30), then click the pencil button ( ![pencil](https://user-images.githubusercontent.com/31810999/46429953-16302380-c71e-11e8-9938-654a235eb53a.png) ) on the top bar, on the right side, to clone that file so you can edit it.  
You make your changes (update the address) and then go to the bottom of the page and press the button to finish. Proceed on the next pages to create a "pull-request" (a summary of the changes you made on your clone so they can be merged back to the original, making your changes official).  

Only the owner can approve any final changes btw, so after you create your PR it'll stay in the [pull-requests area](https://github.com/I-A-C/LambdaScrapers/pulls) for the owner to judge.

**Comment by jewbmx** [comment]
Good to know but i dont think itd be simple changes lol, each one will probably need a rewrite to work with the new urls.

**Comment by jewbmx** [comment]
Looks like couchtuner went down again. Also im gonna be working on all the scrapers i have this weekend and will try to share my edits when im done. Imma Yoda guy tho so someone else will have to test them in other addons.

**Comment by jewbmx** [comment]
@doko-desuka or anyone else wanna test run some scrapers i zipped up? Think there was 38 left http://jewrepo.cf/JewRepo/Scrapers/
